import asyncio
from typing import Dict, List, Any
from ace.core.models import Playbook
from ace import database
from ace.similarity import SimilarityService, get_similarity_service
import numpy as np

class Curator:
    """
    The Curator component of the ACE framework.

    The Curator is responsible for the critical task of integrating insights,
    generated by the Reflector, into the playbook. Its primary function is to
    maintain the quality, integrity, and coherence of the playbook. To achieve
    this, it employs a semantic deduplication process, which prevents the
    addition of insights that are conceptually similar to existing entries.

    This process involves generating a vector embedding for each new insight
    and comparing it against the embeddings of existing entries in the playbook.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initializes the Curator.

        This sets up the Curator with the necessary services, such as the
        `SimilarityService` for semantic comparisons, and initializes a lock
        to ensure thread-safe operations on the playbook.

        Args:
            config: A dictionary containing the application configuration.
        """
        self.similarity_service: SimilarityService = get_similarity_service(config)
        self.lock = asyncio.Lock()

    async def curate(self, playbook: Playbook, insights: List[Dict[str, Any]]):
        """
        Asynchronously integrates a list of insights into the playbook.

        This method iterates through the provided insights and, for each one,
        checks if it is a valuable addition to the playbook. It uses semantic
        deduplication to avoid adding conceptually redundant information.

        The process for each insight is as follows:
        1. Check if the exact content already exists.
        2. If not, generate a vector embedding for the insight's content.
        3. Check if any existing entry is semantically similar to the new one.
        4. If no similar entry is found, add the new insight to the playbook.

        Args:
            playbook: The playbook instance to be updated.
            insights: A list of insights to be considered for addition. Each
                      insight is a dictionary, expected to have 'content' and
                      'metadata' keys.
        """
        async with self.lock:
            for insight in insights:
                content = insight.get("content", "")
                if content and not await database.content_exists(content):
                    embedding = self.similarity_service.get_embedding(content)
                    if not await database.is_similar_embedding_present(self.similarity_service, embedding):
                        await playbook.add_entry(
                            content=content,
                            metadata=insight.get("metadata", {}),
                            embedding=embedding.tobytes()
                        )
